name: Build LaTeX document
on: 
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: Continuous Integration
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ml-mol-sciences-report.tex
          post_compile: "latexmk -c"

      - name: Copy to gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
        run: |
          git config --local user.email "jannick.stuby@gmail.com"
          git config --local user.name "${{CI_COMMIT_AUTHOR}}"
          git add ml-mol-sciences-report.pdf
          git commit -m "${{CI_COMMIT_MESSAGE}}"
          git push --set-upstream origin gh-pages