name: Build LaTeX document
on: 
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Check for changed files
        uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          filters: |
            tex:
              - '**/*.tex'


      - name: Compile LaTeX document
        if: ${{ steps.changes.outputs.tex == 'true' }}
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ml-mol-sciences-report.tex
          post_compile: "latexmk -c"
      
      - name: Move pdf to runner temp
        if: ${{ steps.changes.outputs.tex == 'true' }}
        run: |
          mv ml-mol-sciences-report.pdf ${{ runner.temp }}

      - name: Checkout gh-pages
        if: ${{ steps.changes.outputs.tex == 'true' }}
        uses: actions/checkout@v3
        with:
          ref: gh-pages
        
      - name: Move pdf from runner temp
        if: ${{ steps.changes.outputs.tex == 'true' }}
        run: |
          mv ${{ runner.temp }}/ml-mol-sciences-report.pdf .
        
      - name: commit to gh-pages
        if: ${{ steps.changes.outputs.tex == 'true' }}
        run: |
          git config --local user.email "jannick.stuby@gmail.com"
          git config --local user.name "Continuous Integration"
          git add ml-mol-sciences-report.pdf
          git commit -m "Continuous Integration Build Artifacts"
          git push --set-upstream origin gh-pages
